### ISSUE TITLE
xdg-6.0.1 is missed on pypi

### ISSUE THREAD

**Issue by catap** [srstevenson/xdg-base-dirs#209]
Rigth now https://pypi.org/project/xdg-base-dirs/ contains version 6.0.1 and https://pypi.org/project/xdg/ had only 6.0.0.

Shall it be updated as well?

**Comment by srstevenson** [comment]
This is by design: xdg was renamed to xdg-base-dirs to address an import conflict with [PyXDG](https://pypi.org/project/pyxdg/). xdg remains on PyPI for consumers who depend on the original package name but won't receive any further updates. Please migrate to xdg-base-dirs for newer versions such as 6.0.1.
